import { lazy, Suspense, useEffect, useMemo, useState, type FormEvent } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { useRegisterSW } from 'virtual:pwa-register/react';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, BookOpen, Check, CheckCircle2, ChevronRight, CircleHelp, CloudOff, Database, Download, Eye, EyeOff, FileUp, Globe2, HardDrive, LayoutDashboard, Leaf, LoaderCircle, LockKeyhole, Menu, Moon, Plus, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, Sun, Wallet, WifiOff, X } from 'lucide-react';
import { db, createBackup, restoreBackup, saveManualQuote } from '../storage/db';
import { refreshSymbol } from '../storage/market';
import { defaultSettings, natureLabel, quoteAge, selectQuote, settingsSchema, symbolSchema, type Backup, type HistoryPoint, type Instrument, type Quote, type Settings } from '../../../../packages/domain';
import { date, dateTime, decimal, money, percent } from '../../../../packages/domain/format';
import { backupFromText, backupToCSV, downloadFile, parseQuoteCSV, quoteTemplate } from '../../../../packages/import-export';
import type { summarizeHistory } from '../../../../packages/quantitative/history';
import { Modal } from '../components/Modal';
import { Methodology } from '../features/methodology/Methodology';
import { PortfolioWorkspace } from '../features/portfolio/PortfolioWorkspace';
const HistoryChart = lazy(() => import('../components/HistoryChart'));
type Page = 'overview' | 'transactions' | 'watchlist' | 'instruments' | 'data' | 'methodology';
const pages = [{ id: 'overview', label: 'Visão geral', icon: LayoutDashboard }, { id: 'transactions', label: 'Carteiras e transações', icon: Wallet }, { id: 'instruments', label: 'Instrumentos', icon: BarChart3 }, { id: 'watchlist', label: 'Lista de observação', icon: Eye }, { id: 'data', label: 'Dados e definições', icon: Settings2 }, { id: 'methodology', label: 'Metodologia', icon: BookOpen }] as const;
const pageFromHash = (): Page => pages.some(p => p.id === location.hash.slice(1)) ? location.hash.slice(1) as Page : 'overview';
const errorText = (error: unknown) => error instanceof Error ? error.message.startsWith('[') ? 'Os dados não correspondem ao formato esperado. Verifique os campos e a versão do ficheiro.' : error.message : 'Não foi possível concluir a operação.';
const localDateTime = () => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };

export function App() {
  const instruments = useLiveQuery(() => db.instruments.toArray()) ?? [];
  const quotes = useLiveQuery(() => db.quotes.toArray()) ?? [];
  const history = useLiveQuery(() => db.history.toArray()) ?? [];
  const settings = useLiveQuery(() => db.settings.get('main')) ?? defaultSettings;
  const portfolioCount = useLiveQuery(() => db.portfolios.count()) ?? 0;
  const [page, setPage] = useState<Page>(pageFromHash);
  const [mobileNav, setMobileNav] = useState(false);
  const [online, setOnline] = useState(navigator.onLine);
  const [dark, setDark] = useState(false);
  const [toast, setToast] = useState<{ text: string; error?: boolean } | null>(null);
  const [add, setAdd] = useState(false);
  const [manual, setManual] = useState<Instrument | null>(null);
  const [detail, setDetail] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [chartSymbol, setChartSymbol] = useState('VWCE.DE');
  const { needRefresh: [needRefresh], offlineReady: [offlineReady], updateServiceWorker } = useRegisterSW({
    immediate: true,
    onRegisterError: () => setToast({ text: 'Não foi possível preparar o modo offline. Mantenha a ligação e recarregue para tentar novamente.', error: true }),
  });
  const notify = (text: string, error = false) => setToast({ text, error });
  const patchSettings = async (patch: Partial<Settings>) => {
    try { await db.settings.update('main', patch); } catch (error) { notify(errorText(error), true); }
  };
  useEffect(() => { const update = () => setPage(pageFromHash()); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  useEffect(() => { const update = () => setOnline(navigator.onLine); window.addEventListener('online', update); window.addEventListener('offline', update); return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update); }; }, []);
  useEffect(() => {
    const media = matchMedia('(prefers-color-scheme: dark)');
    const update = () => { const enabled = settings.theme === 'dark' || settings.theme === 'system' && media.matches; setDark(enabled); document.documentElement.dataset.theme = enabled ? 'dark' : 'light'; };
    update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update);
  }, [settings.theme]);
  useEffect(() => { if (!toast) return; const timeout = setTimeout(() => setToast(null), 12000); return () => clearTimeout(timeout); }, [toast]);
  const go = (next: Page) => { location.hash = next; setPage(next); setMobileNav(false); window.scrollTo(0, 0); };
  const selected = instruments.find(i => i.symbol === detail);
  const priced = instruments.filter(i => selectQuote(i, quotes)).length;
  const availableHistory = useMemo(() => [...new Set(history.map(p => p.symbol))], [history]);
  const currentChart = availableHistory.includes(chartSymbol) ? chartSymbol : availableHistory[0];
  const chartPoints = useMemo(() => history.filter(p => p.symbol === currentChart).sort((a, b) => a.date.localeCompare(b.date)), [history, currentChart]);
  const latest = [...quotes].sort((a, b) => b.source.retrievedAt.localeCompare(a.source.retrievedAt))[0];
  async function refresh(symbol?: string) {
    if (busy) return;
    if (!settings.proxyUrl) { go('data'); notify('Ligue a fonte gratuita nas definições ou introduza preços manualmente.'); return; }
    setBusy(symbol ?? 'all'); let done = 0; const failures: string[] = []; let missing = 0;
    for (const instrument of instruments.filter(i => !symbol || i.symbol === symbol)) {
      try { const warnings = await refreshSymbol(instrument.symbol, settings.proxyUrl); done++; if (warnings.some(w => w.startsWith('Sem cotação') || w.startsWith('Moeda ausente'))) missing++; }
      catch (error) { failures.push(`${instrument.symbol}: ${errorText(error)}`); }
    }
    setBusy(null);
    notify(failures.length ? `${done} atualizado(s). ${failures.join(' ')}` : `${done} instrumento(s) consultado(s).${missing ? ` ${missing} sem cotação utilizável.` : ''} Metadados não fornecidos continuam em falta.`, failures.length > 0);
  }
  const filtered = instruments.filter(i => `${i.symbol} ${i.name?.value ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  const instrumentTable = <div className="table-scroll"><table className="instrument-table"><thead><tr><th>Instrumento</th><th>Cotação / NAV</th><th>Variação entre observações</th><th>Origem e data</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{filtered.map((instrument, index) => {
    const quote = selectQuote(instrument, quotes);
    const change = quote?.previousClose ? quote.price / quote.previousClose - 1 : null;
    return <tr key={instrument.symbol}><td><button className="instrument-link" onClick={() => setDetail(instrument.symbol)}><span className={`asset-icon color-${index % 4}`}>{instrument.kind === 'nav' ? <Leaf size={19} /> : instrument.symbol.slice(0, 2)}</span><span><strong>{instrument.symbol}</strong><small>{instrument.name?.value ?? 'Nome por obter da fonte'}</small></span></button></td><td className="numeric"><strong>{quote ? money(quote.price, quote.currency, settings.hideValues) : '—'}</strong><small>{instrument.kind === 'nav' ? 'NAV diário' : quote?.currency ?? 'Moeda por confirmar'}</small></td><td>{change !== null ? <><span className={`change ${change >= 0 ? 'positive' : 'negative'}`}>{percent(change, settings.hideValues)}</span><small>{quote?.previousAsOf ? `${date(quote.previousAsOf)} → ${date(quote.source.asOf)}` : 'Face ao fecho anterior da fonte'}</small></> : <span className="muted">Não disponível</span>}</td><td>{quote ? <><span className={`badge ${quote.source.nature === 'observed' ? 'green' : 'amber'}`}>{natureLabel(quote.source.nature)}</span><small>{dateTime(quote.source.asOf)}{quoteAge(quote) > 0 ? ` · há ${quoteAge(quote)} dias` : ''}</small></> : <><span className="badge neutral">Sem dados</span><small>Aguardam consulta ou introdução</small></>}</td><td><button className="icon-button" onClick={() => setManual(instrument)} aria-label={`Introduzir preço de ${instrument.symbol}`}><Plus size={18} /></button></td></tr>;
  })}</tbody></table>{!filtered.length && <div className="empty-search">Nenhum instrumento corresponde à pesquisa.</div>}</div>;

  return <div className="app-shell">
    <a className="skip-link" href="#main">Saltar para o conteúdo</a>
    {mobileNav && <button className="nav-scrim" aria-label="Fechar navegação" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><a href="#overview" className="brand" onClick={() => go('overview')}><span className="brand-mark"><BarChart3 size={23} /></span><span>património<span className="brand-dot">.</span></span></a><div className="workspace-label">O SEU ESPAÇO PESSOAL</div><nav aria-label="Navegação principal">{pages.map(item => <button key={item.id} onClick={() => go(item.id)} className={page === item.id ? 'nav-item active' : 'nav-item'} aria-current={page === item.id ? 'page' : undefined}><item.icon size={19} />{item.label}{page === item.id && <span className="nav-dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="local-card"><span className="local-icon"><ShieldCheck size={21} /></span><strong>Os seus dados são seus.</strong><p>Guardados neste dispositivo.<br />Sem conta. Sem subscrições.</p><button onClick={() => go('data')}>Gerir os meus dados <ArrowUpRight size={14} /></button></div><div className="build-label"><span className="status-dot" /> Edição pessoal <span>v0.2</span></div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={() => setMobileNav(true)} aria-label="Abrir navegação"><Menu size={21} /></button><span>Espaço pessoal</span><ChevronRight size={14} /><strong>{pages.find(p => p.id === page)?.label}</strong></div><div className="top-actions"><span className={`connection ${!online ? 'offline' : ''}`}>{online ? <span className="status-dot" /> : <WifiOff size={14} />}{online ? 'Modo local' : 'Offline'}</span><span className="top-divider" /><button className="icon-button" onClick={() => patchSettings({ hideValues: !settings.hideValues })} aria-label={settings.hideValues ? 'Mostrar valores' : 'Ocultar valores'} title={settings.hideValues ? 'Mostrar valores' : 'Ocultar valores'}>{settings.hideValues ? <EyeOff size={19} /> : <Eye size={19} />}</button><button className="icon-button" onClick={() => patchSettings({ theme: dark ? 'light' : 'dark' })} aria-label={dark ? 'Ativar modo claro' : 'Ativar modo escuro'}>{dark ? <Sun size={19} /> : <Moon size={19} />}</button><span className="profile" aria-label="Espaço privado"><LockKeyhole size={17} /></span></div></header>
    <main id="main" tabIndex={-1}>
      {!online && <div className="notice"><CloudOff size={18} /><span>Está offline. Pode consultar e editar os dados guardados. As cotações mantêm a data da última observação.</span></div>}
      {needRefresh && <div className="notice"><RefreshCw size={18} /><span>Está disponível uma nova versão. Termine as edições antes de atualizar.</span><button onClick={() => updateServiceWorker(true)}>Atualizar aplicação</button></div>}
      {(page === 'transactions' || page === 'watchlist' || page === 'overview' && portfolioCount > 0) && <PortfolioWorkspace mode={page as 'overview' | 'transactions' | 'watchlist'} settings={settings} dark={dark} onInstrument={setDetail} notify={notify} />}
      {page === 'overview' && portfolioCount === 0 && <>
        <div className="page-heading"><div><p className="eyebrow">PASSO A PASSO, NO LONGO PRAZO</p><h1>A sua carteira começa aqui<span className="green-text">.</span></h1><p>Um espaço tranquilo para acompanhar os seus investimentos.</p></div><button className="button primary" onClick={() => setAdd(true)}><Plus size={18} /> Adicionar instrumento</button></div>
        {!settings.onboardingDone && <section className="welcome-banner"><div className="welcome-art" aria-hidden="true"><Wallet size={34} /><span><Leaf size={17} /></span></div><div><div className="inline-label">BEM-VINDO AO PATRIMÓNIO <span className="badge green">Marco 2</span></div><h2>Primeiro, uma boa base.</h2><p>Crie a sua primeira carteira e registe uma entrada de dinheiro. Os seus instrumentos já estão preparados.</p><button className="text-button" onClick={() => go('transactions')}>Criar a minha carteira <ArrowRight size={16} /></button></div><button className="icon-button dismiss" onClick={() => patchSettings({ onboardingDone: true })} aria-label="Dispensar boas-vindas"><X size={18} /></button></section>}
        <div className="stats-grid"><Stat icon={<BarChart3 size={19} />} title="Instrumentos acompanhados" value={String(instruments.length).padStart(2, '0')} note="O seu universo de investimento" /><Stat icon={<CheckCircle2 size={19} />} title="Com cotação disponível" value={`${priced} / ${instruments.length}`} note={priced ? 'Cada preço com a sua origem e data' : 'Adicione preços para começar'} /><Stat icon={<Database size={19} />} title="Fonte de cotações" value={settings.proxyUrl ? 'Yahoo Finance' : 'Local'} note={settings.proxyUrl ? 'Consulta manual · sem API paga' : 'Sem ligação externa configurada'} /><Stat icon={<ShieldCheck size={19} />} title="Subscrições necessárias" value="Nenhuma" note="Dados guardados no seu dispositivo" /></div>
        <div className="overview-grid"><section className="panel chart-panel"><div className="panel-header"><div><h2>Histórico de cotações</h2><p>O contexto por trás de cada instrumento</p></div>{availableHistory.length > 0 && <select aria-label="Instrumento do gráfico" value={currentChart} onChange={e => setChartSymbol(e.target.value)}>{availableHistory.map(s => <option key={s}>{s}</option>)}</select>}</div>{chartPoints.length ? <><div className="chart-caption">{currentChart} <span>· {chartPoints[0].currency} · preços diários, não ajustados</span></div>{settings.hideValues ? <div className="chart-empty"><EyeOff size={30} /><h3>Valores ocultos</h3><p>Ative a visibilidade para consultar o gráfico.</p></div> : <Suspense fallback={<div className="chart-empty"><LoaderCircle className="spin" /></div>}><HistoryChart points={chartPoints} dark={dark} /></Suspense>}<button className="text-button chart-detail-link" onClick={() => setDetail(currentChart)}>Ver fonte e observações <ArrowRight size={15} /></button></> : <div className="chart-empty"><div className="empty-visual"><BarChart3 size={32} /><span className="empty-orbit one" /><span className="empty-orbit two" /></div><h3>Uma história feita de dados reais</h3><p>Ligue a fonte gratuita para consultar o histórico.<br />Até lá, não apresentamos curvas de exemplo.</p><button className="button secondary" onClick={() => go('data')}><Globe2 size={16} /> Configurar fonte</button></div>}<div className="panel-foot"><span className="status-dot" />{latest ? `Última recolha: ${dateTime(latest.source.retrievedAt)}` : 'Sem dados de mercado carregados'}<span>Fontes sempre identificadas</span></div></section>
        <section className="panel setup-panel"><div className="panel-header"><div><h2>Ao seu ritmo</h2><p>Três passos para começar</p></div><Sparkles size={19} /></div><SetupStep number="01" done={!!instruments.length} title="Escolher instrumentos" text="Os oito símbolos pedidos estão incluídos." onClick={() => go('instruments')} /><SetupStep number="02" done={priced > 0} title="Adicionar cotações" text="Ligue o Yahoo ou registe um preço manual." onClick={() => instruments[0] ? setManual(instruments.find(i => i.symbol === 'VWCE.DE') ?? instruments[0]) : setAdd(true)} /><SetupStep number="03" done={false} title="Guardar uma cópia" text="Exporte os seus dados para os ter consigo." onClick={() => go('data')} /><div className="setup-note"><CircleHelp size={16} /><p>Crie uma carteira em Carteiras e transações. A visão geral passa a mostrar posições, dinheiro e resultados.</p></div></section></div>
        <section className="panel"><div className="panel-header"><div><h2>Os seus instrumentos <span className="count-badge">{instruments.length}</span></h2><p>Preços, fontes e datas num só lugar</p></div><button className="text-button" onClick={() => go('instruments')}>Ver todos <ArrowRight size={16} /></button></div>{instrumentTable}</section>
      </>}
      {page === 'instruments' && <><div className="page-heading"><div><p className="eyebrow">O SEU UNIVERSO DE INVESTIMENTO</p><h1>Instrumentos</h1><p>Consulte a origem de cada preço e complete os dados em falta.</p></div><button className="button primary" onClick={() => setAdd(true)}><Plus size={18} />Adicionar instrumento</button></div><section className="panel"><div className="table-toolbar"><label className="search-box"><Search size={18} /><input aria-label="Pesquisar instrumentos" placeholder="Pesquisar por símbolo ou nome…" value={query} onChange={e => setQuery(e.target.value)} /></label><button className="button secondary" disabled={!!busy || !online} onClick={() => refresh()}><RefreshCw size={16} className={busy ? 'spin' : ''} />{busy ? `A consultar ${busy === 'all' ? 'instrumentos' : busy}…` : 'Atualizar cotações'}</button></div>{instrumentTable}</section><div className="subtle-note"><CircleHelp size={16} />Cotações na moeda original. Preços manuais permanecem prioritários até desativar a opção nos detalhes.</div></>}
      {page === 'data' && <DataSettings settings={settings} instruments={instruments} quotes={quotes} history={history} patch={patchSettings} notify={notify} offlineReady={offlineReady} online={online} refresh={() => refresh()} busy={!!busy} />}
      {page === 'methodology' && <Methodology />}
      <footer><span><LockKeyhole size={13} /> Privado por natureza. Local por escolha.</span><button onClick={() => go('methodology')}>Dados e pressupostos <ArrowUpRight size={13} /></button></footer>
    </main></div>
    {toast && <div className={`toast ${toast.error ? 'error' : ''}`} role={toast.error ? 'alert' : 'status'}>{toast.error ? <CircleHelp size={19} /> : <CheckCircle2 size={19} />}<span>{toast.text}</span><button className="icon-button" onClick={() => setToast(null)} aria-label="Fechar mensagem"><X size={16} /></button></div>}
    {add && <AddInstrument onClose={() => setAdd(false)} onAdded={symbol => { setAdd(false); setDetail(symbol); notify('Instrumento adicionado. Os metadados serão obtidos da fonte.'); }} />}
    {manual && <ManualPrice instrument={manual} onClose={() => setManual(null)} onSaved={() => { setManual(null); notify('Preço manual guardado neste dispositivo.'); }} />}
    {selected && !manual && <InstrumentDetail instrument={selected} quotes={quotes} history={history} hidden={settings.hideValues} dark={dark} onClose={() => setDetail(null)} onManual={() => setManual(selected)} refresh={() => refresh(selected.symbol)} busy={!!busy} online={online} notify={notify} />}
  </div>;
}
function Stat({ icon, title, value, note }: { icon: React.ReactNode; title: string; value: string; note: string }) { return <section className="stat-card"><div className="stat-label">{title}<span>{icon}</span></div><div className="stat-value">{value}</div><p>{note}</p></section>; }
function SetupStep({ number, done, title, text, onClick }: { number: string; done: boolean; title: string; text: string; onClick: () => void }) { return <button className="setup-step" onClick={onClick}><span className={`step-number ${done ? 'done' : ''}`}>{done ? <Check size={17} /> : number}</span><span><strong>{title}</strong><small>{text}</small></span><ChevronRight size={17} /></button>; }

function AddInstrument({ onClose, onAdded }: { onClose: () => void; onAdded: (symbol: string) => void }) {
  const [symbol, setSymbol] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { const value = symbolSchema.parse(symbol); if (await db.instruments.get(value)) throw new Error('Este instrumento já está na sua lista.'); await db.instruments.add({ symbol: value, kind: value === '0P0001PBB6.F' ? 'nav' : 'exchange', manualOverride: false, createdAt: new Date().toISOString() }); onAdded(value); } catch (e) { setError(errorText(e)); } finally { setSaving(false); } }
  return <Modal title="Adicionar instrumento" onClose={onClose}><form onSubmit={submit} className="form-stack"><p className="muted">Introduza o símbolo usado no Yahoo Finance. A identidade e os metadados serão confirmados pela fonte.</p><label>Símbolo Yahoo<input autoFocus required maxLength={40} placeholder="Por exemplo, VWCE.DE" value={symbol} onChange={e => setSymbol(e.target.value)} autoCapitalize="characters" /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving}>Adicionar</button></div></form></Modal>;
}
function ManualPrice({ instrument, onClose, onSaved }: { instrument: Instrument; onClose: () => void; onSaved: () => void }) {
  const [price, setPrice] = useState(''); const [currency, setCurrency] = useState(instrument.currency?.value ?? ''); const [asOf, setAsOf] = useState(localDateTime); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { const instant = new Date(asOf); if (!Number.isFinite(instant.getTime()) || instant.getTime() > Date.now()) throw new Error('Indique uma data válida, que não esteja no futuro.'); await saveManualQuote(instrument, decimal(price), currency.trim().toUpperCase(), instant.toISOString()); onSaved(); } catch (e) { setError(errorText(e)); } finally { setSaving(false); } }
  return <Modal title={instrument.kind === 'nav' ? 'Introduzir NAV' : 'Introduzir preço'} onClose={onClose}><form className="form-stack" onSubmit={submit}><div className="form-context"><BarChart3 size={20} /><strong>{instrument.symbol}</strong><span className="badge amber">Manual</span></div><p className="muted">Este valor fica prioritário. A origem manual e a data serão sempre visíveis.</p><div className="form-row"><label>{instrument.kind === 'nav' ? 'NAV por unidade' : 'Preço por unidade'}<input autoFocus inputMode="decimal" required placeholder="123,45" value={price} onChange={e => setPrice(e.target.value)} /></label><label>Moeda ISO<input required maxLength={3} placeholder="EUR" value={currency} onChange={e => setCurrency(e.target.value.toUpperCase())} /></label></div><label>Data e hora da observação<input required type="datetime-local" value={asOf} max={localDateTime()} onChange={e => setAsOf(e.target.value)} /><small>Introduza a hora no fuso do dispositivo. A consulta apresenta horas de Lisboa.</small></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving}>Guardar preço</button></div></form></Modal>;
}

function InstrumentDetail({ instrument, quotes, history, hidden, dark, onClose, onManual, refresh, busy, online, notify }: { instrument: Instrument; quotes: Quote[]; history: HistoryPoint[]; hidden: boolean; dark: boolean; onClose: () => void; onManual: () => void; refresh: () => void; busy: boolean; online: boolean; notify: (text: string, error?: boolean) => void }) {
  const quote = selectQuote(instrument, quotes);
  const points = useMemo(() => history.filter(p => p.symbol === instrument.symbol).sort((a, b) => a.date.localeCompare(b.date)), [history, instrument.symbol]);
  const [summary, setSummary] = useState<ReturnType<typeof summarizeHistory>>(null);
  useEffect(() => { const worker = new Worker(new URL('../workers/history.worker.ts', import.meta.url), { type: 'module' }); worker.onmessage = event => setSummary(event.data.result ?? null); worker.postMessage({ id: 1, points }); return () => worker.terminate(); }, [points]);
  return <Modal title={instrument.symbol} onClose={onClose} wide><p className="muted">{instrument.name?.value ?? 'Nome não disponibilizado pela fonte'}</p><div className="detail-price">{quote ? money(quote.price, quote.currency, hidden) : 'Sem cotação'}{quote && <span className={`badge ${quote.source.nature === 'observed' ? 'green' : 'amber'}`}>{natureLabel(quote.source.nature)}</span>}</div>{quote && <p className="source-line">{quote.source.name} · Observação: {dateTime(quote.source.asOf)}<br />Recolha: {dateTime(quote.source.retrievedAt)}</p>}<div className="detail-actions"><button className="button primary" onClick={onManual}><Plus size={16} />Introduzir {instrument.kind === 'nav' ? 'NAV' : 'preço'}</button><button className="button secondary" disabled={busy || !online} onClick={refresh}><RefreshCw size={16} className={busy ? 'spin' : ''} />Consultar fonte</button></div>
    {instrument.manualOverride && <div className="notice amber-notice"><span>O preço manual tem prioridade.</span><button onClick={async () => { try { await db.instruments.update(instrument.symbol, { manualOverride: false }); notify('Prioridade manual desativada.'); } catch (error) { notify(errorText(error), true); } }}>Usar fonte/importação</button></div>}
    <dl className="metadata-grid">{[['Nome', instrument.name], ['ISIN', instrument.isin], ['Moeda', instrument.currency], ['TER anual', instrument.ter], ['Mercado', instrument.exchange], ['Fuso da fonte', instrument.timezone]].map(([label, value]) => { const field = value as Instrument['name'] | Instrument['ter']; return <div key={label as string}><dt>{label as string}</dt><dd>{field ? typeof field.value === 'number' ? percent(field.value).replace('+', '') : field.value : <span className="muted">Não disponível</span>}</dd>{field && <small>{natureLabel(field.source.nature)} · {field.source.name}<br />Referência: {date(field.source.asOf)}</small>}</div>; })}</dl>
    <h3>Histórico disponível</h3>{points.length && !hidden ? <><p className="muted">{points.length} observações · {points[0].currency} · preços não ajustados</p><Suspense fallback={<p>A preparar gráfico…</p>}><HistoryChart points={points} dark={dark} /></Suspense>{summary && <div className="history-summary"><span>Mínimo do período <strong>{money(summary.min, summary.first.currency)}</strong></span><span>Máximo do período <strong>{money(summary.max, summary.first.currency)}</strong></span></div>}<details><summary>Consultar observações e fontes</summary><div className="observations"><table><thead><tr><th>Data</th><th>Preço</th><th>Fonte</th></tr></thead><tbody>{[...points].reverse().map(p => <tr key={p.id}><td>{date(p.date)}</td><td>{money(p.close, p.currency)}</td><td>{p.source.name}</td></tr>)}</tbody></table></div></details></> : <div className="inline-empty">{hidden ? 'Valores ocultos.' : 'Ainda não existe uma série histórica. Consulte a fonte para a carregar.'}</div>}
  </Modal>;
}

function DataSettings({ settings, instruments, quotes, history, patch, notify, offlineReady, online, refresh, busy }: { settings: Settings; instruments: Instrument[]; quotes: Quote[]; history: HistoryPoint[]; patch: (patch: Partial<Settings>) => Promise<void>; notify: (message: string, error?: boolean) => void; offlineReady: boolean; online: boolean; refresh: () => void; busy: boolean }) {
  const [proxyUrl, setProxyUrl] = useState(settings.proxyUrl); const [testing, setTesting] = useState(false);
  const [restoring, setRestoring] = useState<Backup | null>(null); const [importing, setImporting] = useState<ReturnType<typeof parseQuoteCSV> | null>(null);
  const [processing, setProcessing] = useState(false); const [persistent, setPersistent] = useState<boolean | null>(null); const [guide, setGuide] = useState(false);
  useEffect(() => { setProxyUrl(settings.proxyUrl); }, [settings.proxyUrl]);
  useEffect(() => { navigator.storage?.persisted?.().then(setPersistent).catch(() => setPersistent(false)); }, []);
  async function exportData(format: 'json' | 'csv') { try { const backup = await createBackup(); downloadFile(`patrimonio-${new Date().toISOString().slice(0, 10)}.${format}`, format === 'json' ? JSON.stringify(backup, null, 2) : backupToCSV(backup), format === 'json' ? 'application/json' : 'text/csv;charset=utf-8'); notify('Backup exportado. Guarde-o num local seguro; contém os valores completos.'); } catch (error) { notify(errorText(error), true); } }
  async function load(file: File | undefined, mode: 'restore' | 'quotes') { if (!file) return; try { if (file.size > 30_000_000) throw new Error('O ficheiro excede o limite de 30 MB.'); const text = await file.text(); if (mode === 'restore') setRestoring(backupFromText(text)); else setImporting(parseQuoteCSV(text, instruments)); } catch (error) { notify(errorText(error), true); } }
  async function saveProxy(event: FormEvent) { event.preventDefault(); try { const normalized = proxyUrl.trim().replace(/\/$/, ''); settingsSchema.parse({ ...settings, proxyUrl: normalized }); await patch({ proxyUrl: normalized }); notify(normalized ? 'Fonte configurada. Pode agora consultar as cotações.' : 'Ligação externa desativada.'); } catch (error) { notify(errorText(error), true); } }
  async function testProxy() { setTesting(true); try { const normalized = proxyUrl.trim().replace(/\/$/, ''); settingsSchema.parse({ ...settings, proxyUrl: normalized }); if (!normalized) throw new Error('Introduza primeiro o endereço do Worker.'); const response = await fetch(`${normalized}/api/health`, { credentials: 'omit', referrerPolicy: 'no-referrer', signal: AbortSignal.timeout(10000) }); const data = await response.json(); if (!response.ok || data.service !== 'patrimonio-dados' || data.ok !== true) throw new Error('O endereço não corresponde a um proxy Património acessível.'); notify('Ligação confirmada. Guarde o endereço para o utilizar.'); } catch { notify('Não foi possível ligar. Confirme o endereço, a ligação e a origem autorizada no Worker.', true); } finally { setTesting(false); } }
  return <><div className="page-heading"><div><p className="eyebrow">SIMPLES DE CONFIGURAR. FÁCIL DE GUARDAR.</p><h1>Dados e definições</h1><p>Comece em modo local. Ligue uma fonte gratuita quando quiser.</p></div><span className="badge green"><ShieldCheck size={14} /> Sem subscrições</span></div><div className="settings-grid">
    <section className="panel settings-card"><div className="section-title"><span className="section-icon-wrap"><Globe2 size={22} /></span><div><h2>Fonte de cotações</h2><p>Opcional · Yahoo Finance através do seu Worker</p></div></div><p className="muted">Sem chaves de API. Se preferir, continue com preços manuais e ficheiros CSV.</p><form className="form-stack" onSubmit={saveProxy}><label>Endereço do Worker<input type="url" placeholder="https://patrimonio-dados.seu-nome.workers.dev" value={proxyUrl} onChange={e => setProxyUrl(e.target.value)} /><small>O endereço fica apenas neste dispositivo.</small></label><div className="form-actions left"><button className="button primary">Guardar configuração</button><button type="button" className="button secondary" onClick={testProxy} disabled={testing || !online}>{testing ? <LoaderCircle size={16} className="spin" /> : <Globe2 size={16} />}Testar ligação</button></div></form><button className="text-button spaced" onClick={() => setGuide(!guide)}>{guide ? 'Fechar instruções' : 'Como obter este endereço gratuitamente'} <ChevronRight size={15} /></button>{guide && <div className="guide"><ol><li>Crie uma conta Cloudflare no plano <strong>Free</strong>. Use o subdomínio gratuito, sem comprar domínio.</li><li>Publique a pasta <code>dist</code> no Cloudflare Pages após executar <code>npm run build</code>.</li><li>No ficheiro <code>apps/proxy/wrangler.jsonc</code>, acrescente o endereço do seu site a <code>ALLOWED_ORIGINS</code>.</li><li>Execute <code>npx wrangler deploy --config apps/proxy/wrangler.jsonc</code> numa conta Workers Free e copie o endereço apresentado.</li><li>Cole-o acima, teste a ligação e guarde. Não ative planos pagos ou complementos.</li></ol><p>Instruções completas em <code>docs/deployment.md</code>, na pasta do projeto. A app funciona sem o Worker.</p></div>}<div className="settings-separator" /><button className="button secondary full" disabled={busy || !online || !settings.proxyUrl} onClick={refresh}><RefreshCw size={16} className={busy ? 'spin' : ''} />{busy ? 'A consultar instrumentos…' : 'Consultar cotações agora'}</button><p className="fine-print">Sem consultas automáticas em segundo plano. Quando um limite gratuito é atingido, mantemos os últimos dados locais.</p></section>
    <section className="panel settings-card"><div className="section-title"><span className="section-icon-wrap"><HardDrive size={22} /></span><div><h2>Os seus dados, consigo</h2><p>Backup completo · formato aberto e versionado</p></div></div><div className="storage-counts"><span><strong>{instruments.length}</strong> instrumentos</span><span><strong>{quotes.length}</strong> cotações</span><span><strong>{history.length}</strong> observações</span></div><p className="muted">Exporte todos os dados e preferências. O CSV de backup conserva as relações através de registos estruturados.</p><div className="form-actions left"><button className="button primary" onClick={() => exportData('json')}><Download size={16} />Exportar JSON</button><button className="button secondary" onClick={() => exportData('csv')}><Download size={16} />Exportar CSV</button></div><div className="settings-separator" /><label className="upload-zone"><FileUp size={24} /><strong>Restaurar um backup</strong><span>Escolha um ficheiro JSON ou CSV · até 30 MB</span><input type="file" accept=".json,.csv,application/json,text/csv" aria-label="Restaurar backup" onChange={e => { load(e.target.files?.[0], 'restore'); e.target.value = ''; }} /></label><p className="fine-print">Pode rever o conteúdo antes de substituir os dados. É guardada uma cópia do estado atual antes do restauro.</p></section>
    <section className="panel settings-card"><div className="section-title"><span className="section-icon-wrap"><ArrowDownToLine size={22} /></span><div><h2>Importar cotações</h2><p>Uma alternativa independente da fonte online</p></div></div><p className="muted">Importe preços e metadados com origem identificada. Nome, ISIN e TER são opcionais.</p><button className="text-button" onClick={() => downloadFile('modelo-cotacoes.csv', quoteTemplate(), 'text/csv;charset=utf-8')}><Download size={16} />Descarregar modelo CSV</button><label className="upload-zone compact"><FileUp size={22} /><strong>Escolher CSV de cotações</strong><span>Dados separados por ponto e vírgula ou vírgula</span><input type="file" accept=".csv,text/csv" aria-label="Importar CSV de cotações" onChange={e => { load(e.target.files?.[0], 'quotes'); e.target.value = ''; }} /></label><details><summary>Formato dos campos</summary><p className="fine-print"><code>symbol</code>: símbolo Yahoo; <code>as_of</code>: instante ISO com fuso, como 2026-01-15T17:30:00Z; <code>price</code>: preço positivo; <code>currency</code>: moeda ISO; <code>source</code>: origem consultada. Campos opcionais: <code>name</code>, <code>isin</code>, <code>ter_percent</code> (em percentagem: 0,20 significa 0,20%). Sem linhas fictícias no modelo.</p></details></section>
    <section className="panel settings-card"><div className="section-title"><span className="section-icon-wrap"><Settings2 size={22} /></span><div><h2>À sua maneira</h2><p>Preferências guardadas neste dispositivo</p></div></div><label className="setting-row"><span><strong>Aparência</strong><small>Escolha o ambiente mais confortável.</small></span><select value={settings.theme} onChange={e => patch({ theme: e.target.value as Settings['theme'] })}><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></label><label className="setting-row"><span><strong>Ocultar valores</strong><small>Também oculta os gráficos.</small></span><input type="checkbox" className="switch" checked={settings.hideValues} onChange={e => patch({ hideValues: e.target.checked })} /></label><div className="setting-row"><span><strong>Armazenamento persistente</strong><small>{persistent === true ? 'Proteção concedida pelo navegador.' : 'Reduza o risco de remoção automática dos dados.'}</small></span><button className="button secondary small" disabled={persistent === true} onClick={async () => { try { const allowed = await navigator.storage?.persist?.(); setPersistent(!!allowed); notify(allowed ? 'Proteção do armazenamento ativada.' : 'O navegador não concedeu proteção. Continue a guardar backups.'); } catch { notify('Esta opção não está disponível neste navegador.', true); } }}>{persistent ? 'Protegido' : 'Proteger'}</button></div><div className="offline-card"><ShieldCheck size={20} /><div><strong>{offlineReady || navigator.serviceWorker?.controller ? 'Aplicação preparada para offline' : 'Disponibilidade offline'}</strong><p>Disponível na versão publicada ou em pré-visualização de produção, após a primeira abertura online. Pode instalá-la pelo menu do navegador.</p></div></div></section>
  </div>
  {restoring && <Modal title="Rever restauro" onClose={() => !processing && setRestoring(null)}><div className="form-stack"><p>Backup de {dateTime(restoring.exportedAt)}.</p><div className="notice"><span>{restoring.portfolios.length} carteiras · {restoring.transactions.length} movimentos · {restoring.instruments.length} instrumentos · {restoring.quotes.length} cotações</span></div><p>O restauro substitui os dados e as preferências deste dispositivo, incluindo o endereço do proxy. Vamos descarregar primeiro uma cópia dos dados atuais.</p><p className="fine-print">Proxy do backup: {restoring.settings.proxyUrl || 'Sem ligação externa'}</p><div className="form-actions"><button className="button secondary" disabled={processing} onClick={() => setRestoring(null)}>Cancelar</button><button className="button primary" disabled={processing} onClick={async () => { setProcessing(true); try { const current = await createBackup(); downloadFile(`patrimonio-antes-restauro-${Date.now()}.json`, JSON.stringify(current, null, 2), 'application/json'); await restoreBackup(restoring); setRestoring(null); notify('Backup restaurado com sucesso.'); } catch (error) { notify(errorText(error), true); } finally { setProcessing(false); } }}>Guardar cópia e restaurar</button></div></div></Modal>}
  {importing && <Modal title="Rever importação" onClose={() => !processing && setImporting(null)}><div className="form-stack"><p>{importing.quotes.length} cotações de {importing.instruments.length} instrumentos.</p><p className="muted">{importing.duplicates ? `${importing.duplicates} linha(s) duplicada(s): prevalece a última no ficheiro. ` : ''}Registos com o mesmo símbolo e instante substituem importações anteriores. Preços manuais prioritários mantêm-se.</p><div className="import-preview">{importing.quotes.slice(0, 20).map(q => <div key={q.id}><strong>{q.symbol}</strong><span>{money(q.price, q.currency, settings.hideValues)}</span><small>{dateTime(q.source.asOf)} · {q.source.name}</small></div>)}</div>{importing.quotes.length > 20 && <p className="fine-print">Pré-visualização das primeiras 20 cotações.</p>}<div className="form-actions"><button className="button secondary" disabled={processing} onClick={() => setImporting(null)}>Cancelar</button><button className="button primary" disabled={processing} onClick={async () => { setProcessing(true); try { await db.transaction('rw', [db.instruments, db.quotes], async () => { await db.instruments.bulkPut(importing.instruments); await db.quotes.bulkPut(importing.quotes); }); setImporting(null); notify('Cotações importadas e identificadas com a sua origem.'); } catch (error) { notify(errorText(error), true); } finally { setProcessing(false); } }}>Importar cotações</button></div></div></Modal>}
  </>;
}
