export function LedgerMethodology() {
  return <article className="panel prose ledger-methodology"><h2>Carteiras, transações e património · Marco 2</h2>
    <p>O saldo de cada carteira é mantido em EUR. Compras, vendas e posições iniciais podem usar outra moeda, com câmbio de execução explicitamente indicado em EUR por unidade dessa moeda. A valorização atual usa um câmbio separado, datado e identificado. Sem preço ou câmbio suficiente, o total e os pesos ficam indisponíveis; mostramos apenas o subtotal conhecido.</p>
    <p><strong>Compra:</strong> dinheiro diminui por quantidade × preço × câmbio + comissão convertida. O custo do lote inclui essa comissão. <strong>Venda:</strong> dinheiro aumenta pelo montante vendido menos comissão; ganho realizado = receita líquida − custo imputado aos lotes. FIFO usa primeiro os lotes mais antigos da mesma carteira e símbolo; também pode escolher um lote específico. Isto não é um simulador fiscal.</p>
    <p>Quantidades, preços e câmbios são strings decimais com até 12 casas. O motor usa inteiros BigInt à escala de 10¹², arredondamento ao mais próximo (meios afastados de zero) e liquidação monetária em cêntimos. Nas vendas parciais, o custo é repartido proporcionalmente; a última parcela recebe o custo residual integral. Nenhum custo desaparece por arredondamento.</p>
    <p><strong>Património = dinheiro + soma dos valores de mercado.</strong> Valor de cada posição = unidades × cotação do instrumento × câmbio de valorização. Preço médio em EUR = custo remanescente, incluindo comissões de compra, dividido pelas unidades remanescentes. Peso = valor da posição / património total, incluindo dinheiro. Ganho não realizado = valor de mercado − custo remanescente.</p>
    <p><strong>Capital líquido</strong> inclui entradas menos levantamentos e valores de abertura declarados. Transferências contam como saída na origem e entrada no destino; anulam-se na vista consolidada. As suas comissões são despesas. Rendimentos recebidos aumentam o resultado, sem aumentar o capital. O total de comissões é informativo e não é deduzido uma segunda vez.</p>
    <p><strong>Resultado desde o início = património − capital líquido.</strong> Variação de hoje = património atual − património de ontem − fluxos externos líquidos de hoje. É uma variação monetária, não TWR ou XIRR. Comissões e rendimentos do dia fazem parte do resultado. Sem valorização anterior completa, a variação diária fica indisponível.</p>
    <p>Uma <strong>posição inicial</strong> é um ponto de partida quando não existe histórico completo: informa unidades, custo de aquisição e valor de mercado total em EUR na data de abertura. Esse valor define o capital de abertura, sem criar dinheiro ou cotação fictícia. O resultado de acompanhamento começa nessa data; ganhos por lote podem incluir valorização anterior. A diferença entre essas bases é preservada pelo motor.</p>
    <p>O gráfico usa uma grelha diária em Europe/Lisbon. Em cada dia, aplica os movimentos por instante e ordem de registo e usa a última observação de preço/NAV e câmbio disponível até à data. Não preenche antes da primeira observação. Feriados e atrasos de NAV ficam identificados como valores transportados. Hoje é uma fotografia com os dados disponíveis, não necessariamente um fecho definitivo. Séries recebidas posteriormente permitem reconstrução histórica, mas não garantem reproduzir a informação que era conhecida em tempo real.</p>
    <p>As datas de preço e câmbio são visíveis por posição; preços manuais e importados conservam a sua origem. O gráfico deixa lacunas onde faltam dados. Não são utilizados preços de execução como substitutos silenciosos de cotações de mercado. Desdobramentos e outros eventos societários ainda não são aplicados automaticamente: esta versão requer movimentos e quantidades já reconciliados com o extrato.</p>
    <p>Alterar ou eliminar um movimento volta a validar toda a sequência, incluindo os movimentos posteriores. Sem vendas a descoberto ou saldos negativos. Operações no mesmo instante seguem a ordem de registo; no CSV, a ordem das linhas decide novos movimentos empatados. Importações são atómicas e identificadores repetidos com dados diferentes são bloqueados.</p>
    <p>Os backups da versão 2 incluem carteiras, movimentos, câmbios e lista de observação. Backups da versão 1 continuam aceites e são convertidos com estas listas vazias. A confirmação de restauro mostra os totais e substitui integralmente o estado local.</p>
    <p>Estas convenções distinguem movimentos externos de resultados de investimento; não constituem uma declaração de conformidade GIPS. <a href="https://www.gipsstandards.org/standards/gips-standards-for-firms/gips-standards-handbook-for-firms/" target="_blank" rel="noreferrer">Referência conceptual: GIPS, dados e fluxos externos ↗</a></p>
  </article>;
}
