import { BookOpen, CheckCircle2, Database, Clock3 } from 'lucide-react';
import { LedgerMethodology } from './LedgerMethodology';
export function Methodology() {
  return <div className="methodology"><div className="page-heading"><div><p className="eyebrow">TRANSPARÊNCIA, POR PRINCÍPIO</p><h1>Como tratamos os seus dados</h1><p>Fontes identificadas. Pressupostos visíveis. Sem preencher as lacunas.</p></div><BookOpen size={32} /></div>
    <LedgerMethodology />
    <div className="method-grid">
      <article className="panel prose"><Database className="section-icon" /><h2>Uma origem para cada valor</h2><p><strong>Observado:</strong> recebido da fonte indicada. <strong>Importado:</strong> fornecido num ficheiro pelo utilizador, sem verificação independente. <strong>Manual:</strong> introduzido pelo utilizador. Dados em falta aparecem como «Não disponível».</p><p>Nome, ISIN, moeda e TER não são inferidos a partir do símbolo. A resposta de cotações do Yahoo pode não conter ISIN ou TER; estes campos podem ser importados com fonte identificada.</p></article>
      <article className="panel prose"><Clock3 className="section-icon" /><h2>O preço tem uma data</h2><p>Mostramos a data da observação e a data da recolha separadamente. As horas apresentadas usam Europe/Lisbon. A indicação «há N dias» conta dias completos de 24 horas, sem inferir se houve sessão de bolsa.</p><p>O PPR usa NAV diário e mostra a variação entre os dois NAV disponíveis, com as datas. Não possui volume nem visualização intradiária.</p></article>
      <article className="panel prose"><CheckCircle2 className="section-icon" /><h2>Cotações e variação</h2><p>Variação entre observações: <code>(preço atual / preço anterior − 1) × 100</code>. Só é apresentada quando existe preço anterior na mesma moeda. Esta medida não é a rendibilidade de uma carteira.</p><p>O gráfico usa preços diários não ajustados, na moeda indicada, sem conversão para EUR, preenchimento de feriados ou reconstrução por holdings. Uma observação da sessão em curso pode ainda mudar. Desdobramentos ou distribuições podem causar quebras: este gráfico não mede retorno total.</p></article>
      <article className="panel prose"><BookOpen className="section-icon" /><h2>Prioridade e limitações</h2><p>Um preço manual fica prioritário até desativar essa opção. Atualizações automáticas não o substituem. Sem prioridade manual, escolhemos a observação mais recente entre a fonte e as importações; em empate, a recolha mais recente.</p><p>Os metadados importados incluem uma data de referência declarada. A data de referência dos metadados Yahoo corresponde à recolha, pois a resposta não informa a sua data efetiva.</p><p>O histórico Yahoo solicitado cobre até dois anos. «Máximo do período» refere-se apenas às observações recebidas; não é um máximo histórico absoluto.</p></article>
    </div>
    <article className="panel prose"><h2>Privacidade, custos e funcionamento offline</h2><p>Instrumentos, preços, preferências e backups ficam no dispositivo, em IndexedDB. O proxy recebe apenas o símbolo consultado. Não usamos publicidade, telemetria, fontes tipográficas externas ou serviços pagos.</p><p>Depois da primeira abertura online da versão publicada, a aplicação pode abrir offline. Novas cotações exigem ligação. A cache do proxy dura 15 minutos para instrumentos de bolsa e 6 horas para NAV. Não existem atualizações automáticas periódicas.</p><p>O plano Workers Free e o subdomínio gratuito Pages evitam despesas de alojamento. Se os limites gratuitos forem atingidos, a atualização pode falhar e os dados locais mantêm-se. A aplicação não altera o plano da conta Cloudflare.</p><p>O armazenamento do navegador pode ser apagado. Exporte regularmente um backup e use «Proteger armazenamento» nas definições. Ocultar valores é uma ajuda visual, não encriptação; os ficheiros exportados contêm os valores completos.</p><p>Esta versão inclui dados de mercado e contabilidade de carteiras. TWR, XIRR, análise de risco, backtesting e planeamento serão entregues nos marcos seguintes, com documentação e testes próprios.</p><div className="source-links"><a href="https://help.yahoo.com/kb/finance/article-exchanges-data-delays-sln2310.html" target="_blank" rel="noreferrer">Fontes e atrasos do Yahoo ↗</a><a href="https://developers.cloudflare.com/workers/platform/pricing/" target="_blank" rel="noreferrer">Limites gratuitos da Cloudflare ↗</a></div></article>
  </div>;
}
