// Capturas de teste em contexto de navegador isolado. Nunca grava no perfil do utilizador.
import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
mkdirSync('artifacts', { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, colorScheme: 'light', reducedMotion: 'reduce' });
page.on('pageerror', error => console.log('page-error', error.message));
await page.goto('http://127.0.0.1:4173/#transactions');
await page.getByRole('button', { name: 'Nova carteira', exact: true }).click();
await page.getByLabel('Nome da carteira').fill('Dados sintéticos · teste visual');
await page.getByRole('button', { name: 'Guardar carteira' }).click();
await page.getByRole('dialog').waitFor({ state: 'hidden' });
const portfolio = 'Dados sintéticos · teste visual';
const header = 'id;portfolio;at;kind;symbol;quantity;price;currency;fx_rate;fee;amount;to_portfolio;lot_id;opening_value;note';
const csv = `${header}\n1;${portfolio};2026-09-28T12:00:00Z;deposit;;;;EUR;1;0;5000;;;0;Dados sintéticos\n2;${portfolio};2026-09-28T13:00:00Z;buy;VWCE.DE;20;100;EUR;1;1;0;;;0;Dados sintéticos\n3;${portfolio};2026-09-29T13:00:00Z;buy;VUAA.DE;10;100;EUR;1;1;0;;;0;Dados sintéticos`;
await page.getByLabel('Importar movimentos CSV', { exact: true }).setInputFiles({ name: 'fixture.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) });
await page.getByRole('button', { name: 'Confirmar importação' }).click();
await page.getByRole('dialog').waitFor({ state: 'hidden' });
await page.getByRole('button', { name: 'Dados e definições', exact: true }).click();
const prices = 'symbol;as_of;price;currency;source\nVWCE.DE;2026-09-28T17:00:00Z;100;EUR;Dados sintéticos de teste\nVWCE.DE;2026-09-29T17:00:00Z;102;EUR;Dados sintéticos de teste\nVWCE.DE;2026-09-30T17:00:00Z;103;EUR;Dados sintéticos de teste\nVUAA.DE;2026-09-29T17:00:00Z;100;EUR;Dados sintéticos de teste\nVUAA.DE;2026-09-30T17:00:00Z;104;EUR;Dados sintéticos de teste';
await page.getByLabel('Importar CSV de cotações', { exact: true }).setInputFiles({ name: 'fixture-prices.csv', mimeType: 'text/csv', buffer: Buffer.from(prices) });
await page.getByRole('button', { name: 'Importar cotações', exact: true }).click(); await page.getByRole('dialog').waitFor({ state: 'hidden' });
await page.getByRole('button', { name: 'Visão geral', exact: true }).click();
await page.getByLabel('Carteira apresentada').selectOption({ label: portfolio });
await page.getByRole('img', { name: /Evolução do património/ }).waitFor();
await page.getByRole('button', { name: 'Fechar mensagem' }).click().catch(() => {});
await page.screenshot({ path: 'artifacts/portfolio-desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Ativar modo escuro' }).click();
await page.screenshot({ path: 'artifacts/portfolio-dark.png', fullPage: true });
await page.getByRole('button', { name: 'Ativar modo claro' }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'artifacts/portfolio-mobile.png', fullPage: true });
console.log('mobile-layout', await page.evaluate(() => ({ width: innerWidth, content: document.documentElement.scrollWidth })));
await browser.close();
