import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
mkdirSync('artifacts', { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, colorScheme: 'light' });
page.on('console', message => { if (['error', 'warning'].includes(message.type())) console.log(message.type(), message.text()); });
page.on('pageerror', error => console.log('pageerror', error.message));
page.on('response', response => { if (response.status() >= 400) console.log('http-error', response.status(), response.url()); });
await page.goto('http://127.0.0.1:4173');
await page.getByRole('heading', { name: 'A sua carteira começa aqui.' }).waitFor();
await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Ativar modo escuro' }).click();
await page.screenshot({ path: 'artifacts/dark.png', fullPage: true });
await page.getByRole('button', { name: 'Ativar modo claro' }).click();
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, colorScheme: 'light', reducedMotion: 'reduce' });
await mobile.goto('http://127.0.0.1:4173');
await mobile.getByRole('heading', { name: 'A sua carteira começa aqui.' }).waitFor();
console.log('mobile-width', await mobile.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, wide: [...document.querySelectorAll('body *')].filter(e => e.getBoundingClientRect().right > innerWidth + 1 && !e.closest('.table-scroll')).map(e => ({ tag: e.tagName, class: String(e.className), right: e.getBoundingClientRect().right, width: e.getBoundingClientRect().width, position: getComputedStyle(e).position })) })));
console.log('mobile-layout', await mobile.evaluate(() => [...document.querySelectorAll('main, .app-shell, .main-shell, .page-heading, .welcome-banner, .stats-grid, .overview-grid, .panel, .table-scroll, footer')].map(e => ({ class: e.className || e.tagName, width: e.getBoundingClientRect().width, right: e.getBoundingClientRect().right, overflow: getComputedStyle(e).overflow }))));
await mobile.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
console.log('service-worker', await page.evaluate(async () => ({ registrations: (await navigator.serviceWorker.getRegistrations()).map(registration => ({ scope: registration.scope, active: registration.active?.state, installing: registration.installing?.state })), controlled: !!navigator.serviceWorker.controller })));
await browser.close();
